#!/bin/bash

case "$1" in
    init)
        chmod 755 pipeline/parallel
        chmod 755 pipeline/utils/setup.r
        chmod 755 pipeline/utils/kv
        chmod 755 pipeline/methods/fm/bin/libFM
        chmod 755 pipeline/methods/vw/vw
        mkdir config
        ./pipeline/setup.r
        ;;
    status)
        cat queue
        ;;
    add)
        if [ "$2" == "dataset" ] ; then
            ./utils/kv add config/datasets "$3"
        elif [ "$2" == "method" ] ; then
            ./utils/kv add config/methods "$3"
        fi
        ;;
    remove)
        if [ "$2" == "dataset" ] ; then
            ./utils/kv remove config/datasets "$3"
        elif [ "$2" == "method" ] ; then
            ./utils/kv remove config/methods "$3"
        fi
        ;;
    push) 
        ./pipeline/remotes/datalab
        ;;
    *)
        echo "usage: $0 { }"
        ;;
esac
exit 0
