#!/bin/bash

case "$1" in
    init)
        chmod 755 pipeline/parallel
        chmod 755 pipeline/utils/kv
        chmod 755 pipeline/splits/*
        chmod 755 pipeline/methods/fm/bin/libFM
        chmod 755 pipeline/methods/vw/vw
        for count in {0..5}
        do
            mkdir -p logs/$count/train
            mkdir -p logs/$count/test
            mkdir -p predictions/$count/train
            mkdir -p predictions/$count/test
        done
        mkdir -p features
        mkdir -p config
        touch config/queue
        touch config/datasets
        touch config/methods
        ;;
    status)
        cat queue
        ;;
    add)
        if [ "$2" == "dataset" ] ; then
            ./utils/kv add config/datasets "$3"
        elif [ "$2" == "method" ] ; then
            ./utils/kv add config/methods "$3"
        fi
        ;;
    remove)
        if [ "$2" == "dataset" ] ; then
            ./utils/kv remove config/datasets "$3"
        elif [ "$2" == "method" ] ; then
            ./utils/kv remove config/methods "$3"
        fi
        ;;
    split) 
        ./pipeline/splits/$2 --K $3 $4
        ;;
    feature)
        ;;
    eval) 
        
        ;;
    push) 
        ./pipeline/remotes/datalab
        ;;
    *)
        echo "usage: $0 { }"
        ;;
esac
exit 0
