#!/usr/bin/env Rscript
suppressPackageStartupMessages(library("optparse"))
option_list <- list(
  make_option("--infile", help="Data file for computing feature."),
  make_option("--outfile",help="Location to save feature file.")
  )
parser <- OptionParser(usage = "%prog [options]", option_list=option_list)
opts   <- parse_args(OptionParser(option_list=option_list))

x <- read.csv(opts$infile)
x <- x[,-1]
write.csv(x,file=opts$outfile,row.names=FALSE)
