#!/bin/bash

# Setup the test environment.
rm -rf example
cp -r ../example .
cd example
rm pipeline; ln -s ../.. pipeline # Fix symlink to pipeline.
source pipeline/startup

# Run the test (at this point, the test is in our parent directory).
../$1
if [ $? -eq 0 ]; then
    echo '[pass]'
else
    echo '[fail]'
fi

# Cleanup the test environment.
cd ..
rm -rf example
