#!/usr/bin/env Rscript
suppressPackageStartupMessages(library("optparse"))
suppressPackageStartupMessages(library("rjson"))
suppressPackageStartupMessages(library("arm"))

option_list <- list(
  make_option("--id", help=""),
  make_option("--train", help=""),
  make_option("--test", help=""),
  make_option("--predictions", help=""),
  make_option("--log", help="")
)
opts   <- parse_args(OptionParser(option_list=option_list))

config <- fromJSON(,"config.json")
formula <- config$method[['glm']]$formula
if (is.null(formula)) {
    formula <- 'response ~ .'
}

args <- config$method[['glm']]$args[[as.numeric(opts$id) + 1]]  # id uses 0-based indexing

desc <- paste("glm",opts$id,sep="_")

train <- read.csv(fifo(opts$train))
test  <- read.csv(fifo(opts$test))

fit <- bayesglm(as.formula(formula),family=args$family,data=train)
yhat <- predict(fit,type="response",newdata=test)
out <- paste(yhat,collapse="\n")
out <- paste("\"predictions\"",out,sep="\n")
write(out,file=opts$predictions)
